# Generated by Django 6.0 on 2026-02-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, unique=True, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=30, null=True, unique=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусели',
                'db_table': 'Carousel',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Carousel_images', verbose_name='Изображение')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.carousel', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Изображение карусели',
                'verbose_name_plural': 'Изображения карусели',
            },
        ),
    ]
