# Generated by Django 6.0 on 2026-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('page_type', models.CharField(choices=[('about', 'About Page')], max_length=20)),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='PageContentContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('content_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('content_email', models.EmailField(blank=True, max_length=125, null=True, verbose_name='Электронная почта')),
                ('page_type', models.CharField(choices=[('contacts', 'Contacts Page')], max_length=20, verbose_name='Выберите страницу')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
    ]
